### ISSUE TITLE
JS nothing found

### ISSUE THREAD

**Issue by bueltge** [iseulde/administrate#1]
Hi @avryl 
I think the plugin is a nice idea, especially for the WP API.
But in a short test of your plugin I have the error, that can't find the js `bundle.js`, was added to the footer.

``` php
<script type="text/javascript" src="/wp-plugins/administrate/js/bundle.js"></script>
```

You reference this also in the source, but I can't find it.

Thanks. Best regards.

**Comment by ellatrix** [comment]
How did you find this repo? :) I didn't really want anyone to know about it yet.
In short, this repo just has the development files, you need to build it before you can use it. `npm install` and `grunt build`.

**Comment by ellatrix** [comment]
P.S.: Don't expect much.
